In [1]:


import tensorflow as tf

print(tf.__version__)

# for scalar 
x=tf.constant(4.0
             )

x

import numpy as np

#shape
x=tf.constant(4,shape=(1,1))
#<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[4]])>

x

x=tf.constant([[1,2,3],[4,5,6]])
x

x=tf.ones((4,4))
x



x=tf.zeros((8,8))
x

# Diagonal
x=tf.eye(6)
x

#Random
x=tf.random.normal((3,3),mean=1,stddev=0.5)
x=tf.random.uniform((3,3),minval=0,maxval=1)
x

#vector
x=tf.range(9)
x=tf.range(start=2,limit=100, delta=3)
x

#Cast use for DType
x=tf.cast(x,dtype=tf.int32)
x=tf.cast(x,dtype=tf.float64)
x=tf.cast(x,dtype=tf.bool)

x

x=tf.cast(x,dtype=tf.bool)
x



#for add

y=tf.constant([2,3,4])
x=tf.constant([4,54,6])
z=tf.add(x,y)
z=x+y


#for subtruct
z=tf.subtract(x,y)
z=x-y
z

#for divide
z=tf.divide(x,y)
z=x/y
z

#for multiply
z=tf.multiply(x,y)
z=x*y
z

#for multply then sum
z=tf.tensordot(x,y,axes=1)
z=tf.reduce_sum(x*y,axis=0)
z

z=x**4
z




2.11.0


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([    256, 8503056,    1296], dtype=int32)>

InvalidArgumentError: ignored

In [3]:
x=tf.random.normal((2,3))
y=tf.random.normal((2,3))


InvalidArgumentError: ignored

In [8]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [10]:
z=tf.matmul(x,y)

InvalidArgumentError: ignored

# **Indexing**

In [21]:
x=tf.constant([0,12,3,4,2,3,4,5,6,7,8])

In [12]:
x[:]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [13]:
x[1:]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [14]:
x[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [15]:
x[::2
]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [16]:
x[::-1]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int32)>

In [23]:
indices=tf.constant([0,3])
x_ind=tf.gather(x,indices)
x_ind


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 4], dtype=int32)>

In [24]:
x=tf.constant([[1,2],[2,3],[3,4]])


In [25]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int32)>

In [26]:
x[0:]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int32)>

In [27]:
x[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [28]:
x[0:2,:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

### **Reshaping

In [47]:
x=tf.range(9)

In [48]:
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [54]:
x=tf.reshape(x,(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [55]:
x=tf.transpose(x,perm=[1,0])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>

# New Section